# Generated by Django 5.1.5 on 2025-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(blank=True, null=True, unique=True, verbose_name="Телеграмм chat-id"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, null=True, verbose_name="Номер телефона"),
        ),
    ]
