# Generated by Django 5.1.5 on 2025-02-01 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(blank=True, null=True, verbose_name="Место", max_length=250)),
                ("time", models.TimeField(blank=True, null=True, verbose_name="Время")),
                ("action", models.CharField(verbose_name="Действие", max_length=1000)),
                (
                    "sign_pleasant_habit",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Признак приятной привычки", max_length=1000
                    ),
                ),
                (
                    "good_habit",
                    models.CharField(blank=True, null=True, verbose_name="Приятная привычка", max_length=1000),
                ),
                (
                    "periodicity",
                    models.CharField(blank=True, null=True, verbose_name="Периодичность", max_length=1000),
                ),
                ("award", models.CharField(blank=True, null=True, verbose_name="Вознаграждение", max_length=1000)),
                (
                    "time_to_complete",
                    models.CharField(blank=True, null=True, verbose_name="Время на выполнение", max_length=1000),
                ),
                (
                    "sign_publicity",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_habit",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "db_table": "habits",
            },
        ),
    ]
