# Generated by Django 5.1.5 on 2025-02-02 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="sign_pleasant_habit",
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Время на выполнение в секундах"),
        ),
        migrations.CreateModel(
            name="PleasantHabit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(blank=True, null=True, verbose_name="Место")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="Время")),
                ("action", models.CharField(verbose_name="Действие")),
                ("sign_pleasant_habit", models.BooleanField(default=True, verbose_name="Признак приятной привычки")),
                ("sign_publicity", models.BooleanField(default=False, verbose_name="Публикация в общий доступ")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_pleasant_habit",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятные привычки",
                "db_table": "pleasant_habits",
            },
        ),
    ]
