# Generated by Django 5.1.5 on 2025-02-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_remove_habit_sign_pleasant_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="good_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pleasant_habit",
                to="habits.pleasanthabit",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="pleasanthabit",
            name="time",
            field=models.CharField(blank=True, null=True, verbose_name="Время", max_length=1000),
        ),
    ]
