# Generated by Django 5.1.5 on 2025-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_good_habit_alter_pleasanthabit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name="Периодичность"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(blank=True, default="12:00", null=True, verbose_name="Время"),
        ),
    ]
