# Generated by Django 5.1.5 on 2025-02-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_periodicity_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name="Периодичность в неделю"),
        ),
    ]
