# Generated by Django 5.1.5 on 2025-02-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="sign_publicity",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Признак публичной привычки"),
        ),
    ]
