# Generated by Django 5.1.5 on 2025-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_sign_publicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(blank=True, default="12:00", max_length=1000, null=True, verbose_name="Время"),
        ),
    ]
